# Generated by Django 4.2.7 on 2023-12-25 14:03

from django.db import migrations, models
import reservasAPP.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasAPP', '0002_alter_reserva_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='size',
            field=models.IntegerField(validators=[reservasAPP.models.validate_size]),
        ),
    ]
